name: Publish
on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      EXTENSION_OUTPUT: superface-language-client-vscode.vsix
    steps:
      # Checkout project master and setup environment
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Setup Node.js environment
        uses: actions/setup-node@v1.4.4
        with:
          registry-url: "https://npm.pkg.github.com"
          scope: "@superfaceai"

      # Install dependencies and run test
      - name: Install dependencies
        run: yarn install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.SUPERFACE_BOT_PAT }}

      # Build and package
      - name: Build
        run: yarn build
      - name: Package
        run: yarn package --out $EXTENSION_OUTPUT
      
      # Upload asset to the release
      - name: Upload asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./$EXTENSION_OUTPUT
          asset_name: $EXTENSION_OUTPUT
          asset_content_type: application/zip
